bw_mobile_homepage:
    pattern:  /
    defaults: { _controller: BibleWormMobileBundle:Default:index }

bw_get_reading_plan:
    pattern:  /reading-plan
    defaults: { _controller: BibleWormMobileBundle:ReadingPlan:getReadingPlan, _format: html }
    requirements:
        _method: GET
        
bw_get_reading_plan_set:
    pattern:  /reading-plan/{day}
    defaults: { _controller: BibleWormMobileBundle:ReadingPlan:getReadingPlanDay, _format: html }
    requirements:
        _method: GET
        
        
bw_get_reading_plan_passage:
    pattern:  /read/{reference}
    defaults: { _controller: BibleWormMobileBundle:ReadingPlan:getPassage, _format: html, verse: ''}
    requirements:
        _method: GET
        
# bw_get_reading_plan_passage:
#     pattern:  /{book}/{chapter}
#     defaults: { _controller: BibleWormMobileBundle:ReadingPlan:getPassage, _format: html, verse: ''}
#     requirements:
#         _method: GET
#                 
# bw_get_reading_plan_passage_full:
#     pattern:  /{book}/{chapter}/{verse}
#     defaults: { _controller: BibleWormMobileBundle:ReadingPlan:getPassage, _format: html}
#     requirements:
#         _method: GET

bw_get_greek_flash_cards:
    pattern:  /greek-alphabet
    defaults: { _controller: BibleWormMobileBundle:GreekAlphabet:index, _format: html }
    requirements:
        _method: GET