BibleWormSiteBundle:
    resource: "@BibleWormSiteBundle/Resources/config/routing.yml"
    prefix:   /

BibleWormApiBundle:
    resource: "@BibleWormApiBundle/Resources/config/routing.yml"
    prefix:   /api

BibleWormMobileBundle:
    resource: "@BibleWormMobileBundle/Resources/config/routing.yml"
    prefix:   /m

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
