BibleWormPrayerBundle:
    resource: "@BibleWormPrayerBundle/Controller/"
    type:     annotation
    prefix:   /

BibleWormApiBundle:
    resource: "@BibleWormApiBundle/Resources/config/routing.yml"
    prefix:   /api

BibleWormMobileBundle:
    resource: "@BibleWormMobileBundle/Resources/config/routing.yml"
    prefix:   /m

# has to go last because it includes a catch-all route
BibleWormSiteBundle:
    resource: "@BibleWormSiteBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
