parameters:
#    bible_worm_api.example.class: BibleWorm\ApiBundle\Example

services:
#    bible_worm_api.example:
#        class: %bible_worm_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


    bw_api.translation.esv:
        class: BibleWorm\ApiBundle\Bible\Translation\ESV
        calls:
            - [ setKey, [ 'IP' ] ]

    bw_api.bible:
        class: BibleWorm\ApiBundle\Bible\Bible
        calls:
            - [ addTranslation, [ 'ESV', @bw_api.translation.esv ] ]